resources:
  - name: eoc_manifest_gitRepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: skylark05/eoc_manifest
      branch: master

jobs:
  - name: eoc_packages_runCI
    type: runCI
    steps:
      - IN: eoc_manifest_gitRepo
        switch: off
