resources:
  - name: eoc_manifests_gitRepo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: skylark05/eoc_manifests
      branch: master

jobs:
  - name: eoc_packages_runCI
    type: runCI
    steps:
      IN: eoc_manifests_gitRepo
      switch: off
